from pathlib import Path
import json
H=Path(__file__).parent
ops=[]
def add(id,group,label,api,does,supply,returns,agent,detail,examples):
 ops.append(dict(id=id,group=group,label=label,api=api,does=does,supply=supply,returns=returns,agent=agent,detail=detail,examples=examples.split()))
add('create','files','Create a workbook','Workbook.create()', 'Start a new workbook in memory; add sheets and cells to build it out.', 'No existing file is needed. Give each new sheet a name.', 'A workbook object. Adding a sheet returns a worksheet object that later calls can use.', 'Choose the layout, financial rules and content; export and save when a file is needed.', 'A workbook is the whole spreadsheet document. A sheet, worksheet or tab is one page of cells inside it.', 'op:new-workbook')
add('import','files','Open an existing file','SpreadsheetFile.importXlsx(...)', 'Load an .xlsx file into a workbook object that the library can read and edit.', 'The file bytes, loaded with FileBlob.load(path).', 'A workbook object in memory, separate from the source file and any Microsoft Excel window.', 'Check that the imported formulas and features needed for the task survived. Save changes explicitly.', 'The examples combine import with a subsequent action. Their final return reflects that whole code block. Reopening a saved file starts another in-memory working copy.', 'op:reopen-and-edit op:import-add-sheet')
add('save','files','Export and save','SpreadsheetFile.exportXlsx(wb) → file.save(path)', 'Turn the current workbook into an Excel file and write it to disk.', 'The workbook object and a destination path.', 'Export creates a file object. Saving writes it; the tested save call returns undefined, with no verification report.', 'Choose when and where to save; separately reopen or compare the output if assurance is needed.', 'Edits in memory do not update a previously saved file. An already-open Excel window does not show this working copy live.', 'op:final-save op:checkpoint-save op:edit-without-saving old:export')
add('runner','files','Run the script','Codex command tool → Node.js', 'Execute a program that calls the spreadsheet library. This is the outer tool, rather than a spreadsheet operation.', 'A command, working directory and wait/output allowances.', 'Process status, printed output and an exit code; a running process may first return a session ID for later polling.', 'Write the program and decide what to print or save. A successful process exit is not proof of a correct model.', 'The library functions on this page are JavaScript calls, not individual Excel MCP tools. The agent can put many operations in one script.', 'old:runner')
add('map','inspect','List workbook and tabs','wb.inspect({kind: "workbook,sheet", …})', 'Get a structural map without reading all cell contents.', 'The record types and response allowance; optionally request sheet records alone.', 'Workbook counts plus sheet names, IDs and occupied ranges. No cell-value grids for this kind selection.', 'Choose which sheet or area to read next. This is an inventory, not a written explanation of the financial model.', 'inspect is one function with several output choices. “kind” selects the type of records; the adjacent operations use other settings of the same function.', 'lab:map old:sheets')
add('grids','inspect','Read broad value grids','wb.inspect({kind: "table", …})', 'Request cell values for a sheet or combine value grids with a workbook inventory.', 'kind, optional sheet/range, maxChars and fallback preview sizes.', 'Grid dimensions and cell values; possibly full occupied rectangles, sampled values, or omitted records when the response is too large. These are values, not formula text.', 'Notice truncation, narrow the request when useful, and interpret the numbers.', 'Here “table” means an inspection grid, not a named Excel Table. tableMaxRows/Cols are fallback preview limits in the tested runtime: a grid that fits may be returned in full. valuesTruncated means sampled values; outer truncated means omitted records.', 'lab:tab-full lab:tab-small lab:broad lab:all')
add('regions','inspect','Find populated blocks','wb.inspect({kind: "region", …})', 'Locate populated blocks within an area and preview their contents.', 'A sheet, a search rectangle and preview dimensions.', 'Block addresses, sizes, population counts and sample cell values.', 'Judge what each block represents and choose a tighter read when needed.', 'A range is any chosen rectangle of cells, such as A1:D10. A region is a block identified by inspection; it is not another tab. The two Fee engine examples change only preview size.', 'lab:blocks-small lab:blocks-large old:regions')
add('search','inspect','Search labels and text','wb.inspect({kind: "match", …})', 'Find candidate cells by literal text or a regular-expression pattern.', 'Search text/pattern, where to look, match count and response allowance.', 'Matching cell addresses and content, plus a limit notice when applicable.', 'Interpret the match in context. The agent must decide whether “operating result” answers a request about “profit”.', 'This is text matching, not a demonstrated semantic index of the model. A regex is a pattern: management.*fee means “management”, then any characters, then “fee”.', 'lab:search-text lab:search-pattern')
add('ranges','read','Read values and formulas','range.values · range.formulas', 'Read an exact cell or rectangle, including the formula text behind its results.', 'A sheet and cell address or rectangle.', 'Aligned two-dimensional arrays: one for values, another for formula strings. A one-cell read is still a small grid.', 'Choose the addresses; add labels, compare results or assemble a report if needed.', 'A value is the cell’s result; a formula is its calculation rule, such as =SUM(A1:A3). The example script packages both getters together and adds the sheet/range labels.', 'old:ranges')
add('trace','read','Trace dependencies','wb.trace(cell)', 'Follow a result upstream through the cells used in its calculation.', 'The starting cell, including its sheet.', 'A nested tree of cells, values, formulas and their input branches.', 'Interpret the chain and check missing or unexpected branches. A tree is evidence about the imported calculation graph, not an all-model audit.', 'A dependency is a cell used by another cell’s formula. This traces inputs upstream; it is not a report that every downstream output recalculated successfully.', 'old:trace')
add('recalculate','read','Recalculate','wb.recalculate()', 'Ask the library’s calculation engine to update the workbook.', 'The in-memory workbook; no extra parameters in the tested call.', 'Undefined in this run: no automatic list of changed cells or dependency-success report.', 'Read the relevant outputs, compare with expectations, and check errors separately.', 'Fresh formulas updated automatically after an input edit in our small example. An explicit recalculation does not repair dependencies missing during import. This is the library’s engine, not native Microsoft Excel.', 'op:new-recalculation old:recalculate')
add('sheet','edit','Add a sheet','wb.worksheets.add(name)', 'Add a tab to the workbook and use it as a new working area.', 'A sheet name, followed by whichever cells and formatting to populate.', 'A worksheet object for subsequent range, table and chart operations.', 'Choose where the new work belongs and link it to the existing model if needed.', 'Adding a tab does not automatically populate it. The Fee lab example was deliberately created as an illustrative schedule alongside the six original sheets.', 'op:import-add-sheet op:add-linked-build')
add('values','edit','Write or replace values','range.values = [[…]]', 'Put literal numbers, text or blanks into chosen cells.', 'The destination range and a matching grid of values.', 'The cells change. The assignment does not provide a model-health report or a before/after comparison.', 'Choose the right cells and units; read affected results and decide whether the change behaved as intended.', 'Writing a value can replace an existing formula. The examples distinguish an unsaved edit, a deliberate zero and a change that exposed an imported dependency problem.', 'op:edit-without-saving op:zero-input op:restore-valid-input old:value-edit')
add('formulas','edit','Write formulas','range.formulas = [["=…"]]', 'Create a calculation, link sheets, or replace an existing formula.', 'Destination cells and formula strings with the intended references.', 'Formulas are stored and calculated. Read values/formulas separately to see the result.', 'Supply the financial logic, reference rules and missing-input behavior; test representative inputs.', 'Blank-versus-zero handling comes from the formula the agent writes. In the example, an explicit IF/ISBLANK guard makes missing data #N/A while accepting a deliberate zero.', 'op:new-formula op:add-linked-build op:guard-missing-input old:formula-edit')
add('fill','edit','Fill, copy or rebuild formulas','range.fillDown() · fillRight() · copyFrom(...)', 'Extend formulas to nearby cells or copy selected content from another range.', 'Source/destination ranges, fill direction or copy mode.', 'The destination changes; later getters show the resulting formulas and values.', 'Check relative versus fixed references and whether the selected range is appropriate.', 'Relative references move when copied; $-fixed references stay anchored. Rebuilding cleared formulas is a new instruction sequence, not a demonstrated Undo operation.', 'op:rebuild-formulas old:fill old:copy')
add('format','edit','Format cells','range.format · range.setNumberFormat(...)', 'Set fonts, fills, sizes, number formats and other presentation properties.', 'The range and desired formatting properties.', 'Formatting changes on the workbook object. Property assignments do not return a visual-quality judgment.', 'Render the relevant area and inspect readability, clipping and units.', 'Number formatting controls how a value looks; it does not change the underlying calculation. A cell may display two decimals while retaining more precision.', 'op:format-cells')
add('clear','edit','Clear cell contents','range.clear({…})', 'Remove values or formulas from a selected range.', 'The range and the clear option; these examples clear contents.', 'Cell contents disappear. With contents-only clearing, formatting remains.', 'Check dependent outputs and whether blank now means missing, zero or something else in the formulas.', 'Clearing cells does not delete a worksheet or remove the rows themselves. In this example, clearing the quarterly formulas makes their SUM total zero: a plausible-looking result can still be incomplete.', 'op:clear-formulas op:blank-input')
add('table','tables','Create a formal Table','sheet.tables.add(range, hasHeaders, name)', 'Define a named Excel Table over an existing block of cells.', 'The rectangle, whether it includes headers, and the Table name.', 'A Table object. Its values, range and row count can be inspected separately.', 'Choose the correct rectangle and check it does not overlap an existing Table.', 'A formal Excel Table is a named spreadsheet feature inside a tab. It is different from the “table” records returned by inspect. The API accepted an overlapping Table in our unsaved probe, so the documented overlap check is agent work.', 'op:add-table op:recreate-table op:overlap-table')
add('table-row','tables','Append a Table row','table.rows.add(...)', 'Add a row of data to a formal Excel Table.', 'The insertion position or append choice and the row’s values.', 'The Table expands. The tested call returned undefined; a separate read shows the new row.', 'Check the values landed in the intended columns and that any related calculations use them.', 'Appending a Table row is distinct from writing into arbitrary cells below a block. This example adds the Stress scenario to FeeScenarioInputs.', 'op:append-table-row')
add('table-delete','tables','Remove a Table','table.delete()', 'Remove the formal Table object from the sheet.', 'The Table to delete.', 'The Table is removed; in the tested case its underlying cell values remain.', 'Decide whether the cells also need clearing and check references that relied on the Table.', 'Deleting a Table is not the same as deleting its data. Recreating it means calling tables.add again over the retained cells.', 'op:delete-table')
add('chart','visual','Create or update a chart','sheet.charts.add(...) · chart properties', 'Create a chart with cell references for its categories and series; configure its appearance.', 'Chart type, source ranges, title, styling and placement.', 'A chart object. Source-cell changes can then change what the chart displays.', 'Choose a useful chart and valid source ranges; render and judge the result.', 'A cell-bound chart follows its referenced values. The before/after experiment changes the fee assumption while leaving those series references unchanged.', 'op:add-chart op:chart-input-change op:recreate-chart')
add('chart-delete','visual','Remove charts','sheet.charts.deleteAll()', 'Remove charts from a selected sheet.', 'The sheet whose chart collection should be cleared.', 'The chart objects disappear. Their source calculations remain in this example.', 'Confirm the intended charts were removed; rebuild by creating them again if wanted.', 'This demonstrated call deletes all charts on the chosen sheet. It does not erase the cells that supplied their data.', 'op:delete-chart')
add('render','visual','Render an image','wb.render({sheetName, range, …})', 'Generate a picture of a selected workbook area.', 'A sheet, cell range and image settings such as scale and PNG format.', 'An image blob. Writing the bytes to a PNG and opening that image are separate actions.', 'Look at the image and judge labels, layout and charts. Producing pixels does not itself perform that review.', 'Rendering reads the in-memory workbook. It does not take a screenshot of a live Excel window and does not save an .xlsx file.', 'op:render-before op:render-after old:render')
groups=[['files','Open and save'],['inspect','Inspect and locate'],['read','Read and calculate'],['edit','Edit cells and sheets'],['tables','Work with Tables'],['visual','Charts and images']]
(H/'evidence/operations-reference.json').write_text(json.dumps(dict(groups=groups,operations=ops),ensure_ascii=False,indent=2)+'\n')
print(len(ops),'operations')
