from pathlib import Path
import json
HERE=Path(__file__).parent
records={r['id']:r for r in json.loads((HERE/'operations-run/records.json').read_text())}
records['overlap-table']=json.loads((HERE/'operations-run/overlap-table.json').read_text())
# These descriptions are the analyst's interpretation. Captured inputs/results stay separate.
specs=[
('checkpoint-save','files','Save a checkpoint','Write the current workbook to disk.','The saved copy has a 56bp fee margin. save() returns undefined; the hash and re-imported value are checks added by the script.','Export creates a file object; save writes its bytes. No application window is involved.'),
('edit-without-saving','files','Edit without saving','Change the working fee margin from 56bp to 51bp.','Memory changes to 51bp and total fees fall to $1,526.65m. The on-disk copy still says 56bp and its SHA-256 is unchanged.','Changing the workbook object does not save the file. The agent decides when to export.'),
('final-save','files','Export and reopen','Save the completed laboratory and load the saved file again.','The saved file now has the final 60bp input, working formula text and the added formal table. An independent file reader also checks the output.','Export success is one observation. Reading the file back and comparing its contents are extra verification.'),
('reopen-and-edit','files','Edit the saved model','Import the saved output and change the fee margin to 55bp in that new working copy.','Quarter-one fees recalculate to $399.45m, matching a separate arithmetic calculation. The disk copy stays at 60bp because this last experiment is not saved.','Reopening a file starts another in-memory workbook. It does not connect the script to a live Excel window.'),
('new-workbook','create','Create a workbook','Create an empty workbook and add its first worksheet.','Workbook.create() plus worksheets.add() gives a workbook with one tab, Fee calculation. No XLSX has been written yet.','The tab inventory is a separate read. Creating a workbook is not itself file export.'),
('new-formula','create','Write a calculation','Write three inputs and a formula for quarterly fees.','100bn AUM × 50bp annually × a quarter produces $125m. The script separately calculates the same expected answer.','The agent supplies the formula and units. The engine executes that formula.'),
('new-recalculation','create','Change an input','Change the annual fee margin from 50bp to 60bp.','Quarterly fees change from $125m to $150m without an explicit recalculate() call.','Automatic calculation is engine behaviour; reading C5 and comparing it with 150 is agent-written verification.'),
('import-add-sheet','create','Add a tab to Man Group','Import the supplied file and append a Fee lab worksheet.','The six existing tabs remain and a seventh tab is added. The Downloads original is unchanged.','This is an authorised demonstration extension, rather than a rewrite of the original company model.'),
('add-linked-build','create','Add a linked schedule','Build four illustrative quarters, starting from the original Fee engine AUM cell.','New formulas link to Fee engine!W18, grow AUM by 2% per quarter and calculate fees. At 56bp, the four-quarter total is $1,676.33m.','The agent chooses the assumptions, financial logic and cell references. These illustrative quarters are not investment forecasts.'),
('format-cells','create','Format the new area','Set fonts, widths, number formats and input/header colours.','The numbers and formulas stay unchanged. Formatting is a separate set of operations, checked with a style read and later images.','The skill recommends readable, consistent formatting. The agent must choose and apply the settings.'),
('clear-formulas','clear','Clear formula cells','Clear contents in the four quarterly fee cells, preserving formatting.','The four formulas disappear and the total becomes zero because SUM now reads empty cells.','Clearing cells is different from deleting an entire row or tab. A zero total does not prove a model is healthy.'),
('rebuild-formulas','clear','Rebuild the formulas','Write the first formula again and fill it down through all four quarters.','The quarterly calculations and $1,526.65m total return. Relative row references advance; the common assumption remains fixed.','This is an explicit rebuild written by the agent, not an automatic undo command.'),
('blank-input','missing','Clear the input','Remove the fee-margin input while keeping the fee formulas.','The unguarded calculation treats the missing input as zero and returns zero fees.','The library cannot infer whether a blank means missing, not applicable, or deliberately zero.'),
('guard-missing-input','missing','Make missing data visible','Add IF(ISBLANK(...),NA(),...) to the fee formula and fill it down.','With the margin still blank, quarterly fees and the total become #N/A.','This is a model rule supplied by the agent. The error marker is deliberate here, so an error scan must be interpreted.'),
('zero-input','missing','Test a deliberate zero','Enter an explicit zero fee margin.','The guarded formulas calculate zero fees, distinguishing zero from the missing-input case.','The skill calls for blank-versus-zero tests. The particular cells and expected result are agent choices.'),
('restore-valid-input','missing','Restore a valid rate','Set the fee margin to 51bp.','The fees and total return to their earlier values.','Temporary testing must be restored or clearly delivered as an intentional example.'),
('add-table','tables','Create a formal Table','Wrap a separate scenario-input rectangle in a named Excel Table.','FeeScenarioInputs is a real native table object, unlike the table-shaped records in the original broad inspect response.','The cells, headers, table name and range are supplied by the agent. This table is separate from the calculation above it.'),
('append-table-row','tables','Append a table row','Add a fourth scenario to the formal Table.','Stress, 45bp and 0.8 appear in B24:D24.','The append operation adds data. Our explicit range read establishes where it landed.'),
('delete-table','tables','Delete the Table object','Remove the formal Table while watching its cells.','The table count falls from one to zero, but all headers and scenario values remain.','Deleting the Table wrapper is not the same thing as clearing the cells underneath it.'),
('recreate-table','tables','Recreate the Table','Create a named Table again over B20:D24.','One formal Table is present again, now including the appended Stress row.','The agent specifies what to rebuild. There is no automatic restore hidden in this step.'),
('overlap-table','tables','Try an overlapping Table','In a disposable new import, request another Table over D22:F25, overlapping the existing B20:D24 Table.','The API accepts it and the table-name read returns both FeeScenarioInputs and OverlapProbe. No file is saved.','The guide explicitly says to check for overlaps because the API does not reject them. Acceptance in memory does not establish that this is a valid Excel file.'),
('add-chart','charts','Create a linked chart','Create a line chart whose series refers to the quarterly fee cells.','Its series stores cell references to F9:F12 and categories from B9:B12.','A chart object is not a screenshot. The agent explicitly binds source cells and sets its position and appearance.'),
('render-before','charts','Render at 51bp','Render the new sheet and save the returned image.','The chart and table show quarterly fees of $370.40m to $393.07m.','render returns an image blob. Saving its bytes and viewing the PNG are separate steps performed by the agent.'),
('chart-input-change','charts','Change the chart input','Change the fee-margin input from 51bp to 60bp.','The source fees increase to $435.77m–$462.44m while the chart keeps the same range references.','The following image checks what was drawn. Reading the bindings alone is not a visual check.'),
('render-after','charts','Render at 60bp','Render the same area again after the input change.','The plotted line and axis now reflect the larger fee values. Both actual images are available below.','Visual review is recommended in the skill; the library does not itself judge whether the image is readable or financially sensible.'),
('delete-chart','charts','Delete the chart','Remove the drawings in the new sheet’s chart collection.','A drawing inspection finds no matching drawings in Fee lab, while the source cells remain intact.','Deleting presentation does not remove the calculations it was displaying.'),
('recreate-chart','charts','Recreate the chart','Build the chart again against the existing source range.','The new chart binds to the same cells and is included in the final saved XLSX.','The agent restates the source range and formatting. Export preservation is checked separately.')]
cards=[]
for id,group,label,intent,outcome,lesson in specs:
    cards.append(dict(**records[id],group=group,label=label,intent=intent,outcome=outcome,lesson=lesson))
helpers=(HERE/'operations-run.mjs').read_text().split('const cell=')[1].split('const serialize=')[0]
(HERE/'evidence/operations-cards.json').write_text(json.dumps({'cards':cards,'helpers':'const cell='+helpers},indent=2))
print('Prepared',len(cards),'operation records')
