"""Build the field guide's frozen, portable dataset from saved experiments."""
import json,re,shutil,hashlib
from support_catalogue import build_support
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
REF=ROOT.parent/'2026-09-15-artifact-tool-reference'
RUN=REF/'files/runs'
def read(name):return json.loads((RUN/name).read_text())
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2))
FAMILIES=[
 ('workbooks','Workbooks & sheets','Give the model a home','The workbook holds the whole document. Worksheets divide it into named spaces; a range locates cells within one space.','Create, load, rename, reorder, reset and delete.','Workbook → worksheet → range',[['Worksheet name','string','A meaningful name, used in formulas and lookup.'],['Index','integer','Zero-based position in the sheet collection.'],['Reset options','object','Clear cells and remove attached objects separately.']]),
 ('ranges','Cells & ranges','Put facts and rules in the right cells','A range is a rectangular address. It is the main place you read or write values, formulas and formats.','Read, write, fill, copy, merge and clear.','Worksheet → range → cells',[['target.range','A1 address','Which rectangle receives the write.'],['values / formulas','matrix','Rows outside; columns inside.'],['overwrite','allow / error','Use error to reject replacement of populated cells.'],['resize','auto / none','Do not assume this replaces your own bounds checks.']]),
 ('formulas','Calculation','Turn inputs into results','A stored formula defines a relationship. Calculation produces its value; a displayed number alone does not reveal the rule.','Calculate, trace dependencies and inspect spills.','Cell → formula → precedents → value',[['formula','string','Excel-style expression beginning with =.'],['References','A1 or R1C1','Anchor shared inputs with $ where appropriate.'],['Expected result','independent control','Check more than the absence of error tokens.']]),
 ('formatting','Formatting','Help the reader see structure','Formatting changes how cells are read: currency, hierarchy, emphasis and spacing. It usually leaves their stored values intact.','Font, fill, border, alignment, units and freeze panes.','Range → format → font / fill / borders',[['Number format','Excel format code','Changes display, not numeric precision.'],['Color','hex / theme / object','Theme colors can be reused across the workbook.'],['Size','points / pixels / column units','Use explicit units; 30 px is 22.5 row-height points.']]),
 ('rules','Validation & rules','Describe acceptable inputs and visible exceptions','Validation records input rules. Conditional formatting displays conditions. Neither is a substitute for verifying programmatic writes.','Lists, bounds, custom rules, scales, bars and icons.','Range → validation / conditional formats',[['Type','rule token','List, numeric bound, custom formula, color scale and others.'],['Formula / threshold','value or expression','The condition that the rule evaluates.'],['Presentation','format object','What the reader sees when the condition holds.']]),
 ('tables','Excel Tables','Turn a rectangle into a named dataset','An Excel Table adds headers, a name and structured references to a rectangular dataset. It is different from a pivot or a sensitivity grid.','Create, append, style, set headers/totals and remove.','Worksheet → table → data rows',[['range','A1 address','Full table footprint.'],['hasHeaders','boolean','Whether the first row contains field names.'],['showTotals','boolean','Reserve a row: this version does not insert one.'],['rows.add index','null','Appending works; indexed insertion is unsupported.']]),
 ('sensitivity','What-If tables','Ask how one result changes across inputs','A What-If Data Table repeatedly substitutes scenario inputs into an existing calculation and records the results.','One- and two-variable sensitivity grids.','Formula + scenario headers → projected body',[['fullRange','A1 address','Include the corner formula, headers and output body.'],['rowInput','single cell','Replaced by scenario values across the top.'],['columnInput','single cell','Replaced by scenario values down the left.'],['recalculate','method call','Required after constructing the table.']]),
 ('pivots','Pivots & slicers','Summarize records by category','A pivot aggregates source rows. A slicer filters its categories. Cached summaries and the written output area both need checks.','Group fields, aggregate, filter and rebuild caches.','Source → cache → pivot → slicer',[['Source / destination','ranges','Which records are summarized, and where the result appears.'],['Hierarchies','field names','Rows, columns and data measures.'],['Creation route','workbook.pivotTables','The tested root route allows a slicer to find its pivot.']]),
 ('charts','Charts','Give the numbers a visual form','Charts bind a visual object to data. The in-memory object, rendered picture and native Excel chart are separate outputs.','Create, bind, style, annotate, position and remove.','Worksheet ranges → series → chart',[['Type','25 enum tokens','Only 16 emitted native chart XML in the tested fixtures.'],['Data','ranges or arrays','Range references retain the link to workbook cells.'],['Anchor','cells / pixels','Position and size on the worksheet.'],['Labels / data table','existing facade','Mutate nested fields; plain-object replacement can break export.']]),
 ('drawings','Images, shapes & sparklines','Add visual objects and small trends','Images carry pixels, shapes carry geometry and text, and sparklines display a series inside a cell. Each has its own placement and lifecycle.','Add, replace, arrange, style and delete.','Worksheet → drawing or sparkline group',[['Source','bytes / SVG / path','Image insertion does not extract editable cells.'],['Geometry','190 tokens','Custom geometry also needs path commands.'],['Sparkline type','line / column / stacked','Three distinct small-series views.'],['Anchor','from + to / extent','Set at creation or use the supported update operation.']]),
 ('names','Names','Give reusable references a meaning','A defined name gives a range or function a stable name. Scope decides whether it belongs to the workbook or a single sheet.','Named ranges and named LAMBDA functions.','Workbook or worksheet → defined name',[['Name / scope','string / owner','Avoid ambiguous worksheet and workbook definitions.'],['Range','qualified address','The cells a name refers to.'],['lambda','expression','The working property for named functions; not formula.']]),
 ('comments','Comments & notes','Keep explanations beside the cells','Threaded comments record a conversation. A cell note records an annotation. Authors, targets and content are explicit data.','Author, thread, reply, react, resolve and annotate.','Author → thread / note → cell target',[['Author','person identity','Set self before creating comments.'],['Target','cell or range','Where the explanation belongs.'],['Body','text / plainText','Comment and low-level note contracts differ.']]),
 ('inspection','Inspection & discovery','Understand before changing','Help describes available calls. Inspect describes an actual workbook. Resolve turns an inspected identity into an editable object.','Help, inspect, search, resolve and trace.','Question → bounded evidence → editable object',[['kind','record types','Sheets, formulas, tables, charts, threads and names.'],['target','observed anchor ID','Use real IDs returned by inspection.'],['maxChars','integer','Bound the response; check truncation.']]),
 ('files','Files & rendering','Move between representations','Import creates an editable workbook. Rendering creates pixels. Export creates a saved file. Re-import tests a different boundary again.','CSV, Markdown, HTML, XLSX, PNG, JPEG and layout evidence.','Source file → workbook → pixels / native file',[['Format','png / jpeg / layout / xlsx','These are the tested workbook export formats.'],['View','sheet / range / crop','Choose the relevant portion to render.'],['Return type','Blob or saved descriptor','Managed sessions write files and return descriptors.']]),
 ('changes','Changes & sessions','Wrap edits in a repeatable process','Direct edits change an object. Recorded patches describe changes. Shared updates carry collaborative history. Sessions persist work across calls.','Record, apply, undo, replicate and resume.','Code → edit → patch / update → saved session',[['Warnings','returned array','Unknown operations can warn while earlier changes remain.'],['Baseline','shared CRDT history','Identical JSON is not identical collaborative history.'],['Session target','file, snapshot or ID','Reopen the same target across calls.'],['Timeout','1–300,000 ms','Inspect saved state after an ambiguous timeout.']]),
]
families=[dict(zip(['id','label','intent','why','actions','tree','settings'],f)) for f in FAMILIES]
def family(name):
 n=name.lower()
 for key,words in [('sensitivity',['data-table']),('rules',['conditional','validation']),('names',['names.','defined-name']),('pivots',['pivot','slicer']),('comments',['thread','comment','note']),('charts',['chart','axis']),('drawings',['image','shape','sparkline','drawing']),('formatting',['format','style','theme','freeze','gridlines']),('tables',['table']),('ranges',['range','getcell','columnindex','rowindex']),('formulas',['formula','recalculate']),('inspection',['inspect','help','resolve']),('files',['export','render','csv','markdown','html']),('changes',['awareness','record','crdt','session']),('workbooks',['workbook','worksheet','sheet','utils'])]:
  if any(w in n for w in words):return key
 return 'workbooks'
help=[json.loads(s) for s in (RUN/'api-help.ndjson').read_text().splitlines()]
ops=[]
for r in read('ops.json'):
 if r['id']=='OP-invalid':continue
 d=r['detail'];op=d['input']['op'];record={**d,'id':r['id'],'title':op,'family':family(op),'summary':r['description'],'kind':'operation','code':'workbook.apply('+json.dumps([d['input']],ensure_ascii=False,indent=2)+');','status':'Executed','source':'../2026-09-15-artifact-tool-reference/files/runs/ops.json'}
 target=d['input'].get('target');sheet=target.get('sheet') if isinstance(target,dict) else d['input'].get('sheet')
 raw=read('op-'+r['id'][3:]+'.json')
 sh=next((x for x in raw['after']['sheets'] if x['name']==sheet),None)
 if sh:record['cells']=[{k:c.get(k) for k in ['address','value','formula','dataType'] if k in c} for row in sh.get('rows',[])[:6] for c in row.get('cells',[])[:6]]
 ops.append(record)
apis=[]
apiExamples=[(h,e) for h in help if h.get('kind')=='api' for e in h.get('examples',[])]
for r in read('api-example-results.json'):
 h,e=apiExamples[r['index']]
 assert h['name']==r['name']
 capturedInput={**e,'adaptations':r.get('adaptations',[])}
 apis.append(dict(id='api-'+str(r['index']),title=r.get('summary') or r['name'],family=family(r['name']),name=r['name'],summary=h.get('summary',r['name']),kind='api',input=capturedInput,result={k:r[k] for k in ['execution','export','exportError','logs'] if k in r},code=r.get('originalCode') or json.dumps(e,ensure_ascii=False,indent=2),notes=h.get('notes',[]),status='Export fails' if r.get('exportError') else 'Executed',source='../2026-09-15-artifact-tool-reference/files/runs/api-example-'+str(r['index']).zfill(3)+'.json'))
probes={}
for n in ['core','features-first','features-remaining','followup','advanced','recovery']:
 for x in read(n+'.json'):probes[x['id']]={**x,'source':'../2026-09-15-artifact-tool-reference/files/runs/'+n+'.json'}
curated=[
 ('workbooks','C01','Create and organize worksheets','Workbook.create();\nworkbook.worksheets.add(["Alpha", "Beta"]);',{'names':['Alpha','Beta']},None),
 ('ranges','C04','One value and one formula fill differently','range.values = [[7]];\notherRange.formulas = [["=1+1"]];',{'range':'A1:B2','values':[[7]],'formulaRange':'D1:E2','formulas':[['=1+1']]},None),
 ('formulas','C24','Follow a result back to its inputs','workbook.trace("Build!A1");',{'cell':'Build!A1'},None),
 ('formatting','C12','Set readable units and dimensions','sheet.getRange("A1:C1").format.rowHeightPx = 30;\nsheet.getRange("B2:B3").setNumberFormat("#,##0.00;(#,##0.00)");',{'rowHeightPx':30,'format':'#,##0.00;(#,##0.00)'},'formatting.png'),
 ('rules','F02','Validation does not block a JavaScript write','range.dataValidation = {rule:{type:"whole",operator:"between",formula1:1,formula2:10}};\nrange.values = [[999]];',{'allowedRange':[1,10],'programmaticValue':999},None),
 ('tables','V04','Totals can change which rows count','table.showTotals = true;\nsheet.getRange("D2").formulas = [["=SUM(Stock[Qty])+0"]];',{'quantities':[2,3,4],'showTotals':True},None),
 ('sensitivity','F04','Build a two-input sensitivity grid','sheet.dataTables.add("E4:H7", {rowInput:"B2",columnInput:"B3"});\nworkbook.recalculate();',{'fullRange':'E4:H7','rowInput':'B2','columnInput':'B3'},None),
 ('sensitivity','R04','One-variable tables work in this version','sheet.dataTables.add("E4:H5", {rowInput:"B2"});\nworkbook.recalculate();',{'rowInput':'B2','scenarioValues':[1,2,3]},None),
 ('pivots','V05','Filter and refresh a pivot','slicer.selectItems(["North"]);\nslicer.clearFilters();\npivot.rebuildCache();',{'selectItems':['North'],'sourceEdit':{'old':10,'new':100}},None),
 ('charts','A02','Style the existing chart objects','chart.dataLabels.showValue = true;\nchart.dataTable.visible = true;',{'dataLabels.showValue':True,'dataTable.visible':True},'chart-settings.png'),
 ('drawings','R06','Insert an image as a drawing','workbook.fromImage(0, {bytes,contentType:"image/png"}, "F1:H5");',{'target':'F1:H5','contentType':'image/png'},None),
 ('drawings','R05','Add three kinds of sparkline','sheet.sparklineGroups.add({targetRange,sourceData,type:"line"});',{'types':['line','column','stacked']},'sparklines.png'),
 ('names','R02','Define a reusable workbook function','workbook.names.addFunction("AddTax", {lambda:"LAMBDA(amount,amount*1.1)"});',{'name':'AddTax','lambda':'LAMBDA(amount,amount*1.1)'},None),
 ('comments','V02','Attach a native note to a cell','workbook.notes.add(config);',probes['V02']['detail'],None),
 ('inspection','C26','Search and inspect an existing workbook','await workbook.inspect({kind:"sheet,table,formula"});\nworkbook.findCells({searchTerm:"East",sheetId:"Data"});',{'kind':'sheet,table,formula','search':'East'},None),
 ('files','C22','HTML paste keeps the literal formula','const html = source.toHTML(0,"A1:B2",{formulas:true});\ntarget.fromHTML(0,html,"C3");',{'source':'A1:B2','destination':'C3','formulas':True},None),
 ('files','C30','Export, reopen and change an input','await SpreadsheetFile.exportXlsx(workbook);\nawait SpreadsheetFile.importXlsx(file);',{'format':'xlsx'},None),
 ('changes','C28','Record an edit as a replayable patch','const {patch} = workbook.record(() => {\n sheet.getRange("A1").values = [[2]];\n sheet.getRange("B1").formulas = [["=A1*3"]];\n});\notherWorkbook.apply(patch);',{'A1':2,'B1':'=A1*3'},None),
 ('changes','V01','Initialize a replica from shared history','replica.applyCrdtUpdateV2(baseline);\nreplica.applyCrdtUpdateV2(edit,{recalculate:true});',{'baseline':'shared initialization update','edit':'binary CRDT delta'},None),
]
recipes=[]
for fam,pid,title,code,inputs,img in curated:
 p=probes[pid];recipes.append(dict(id='recipe-'+pid,title=title,family=fam,summary=p['description'],kind='guided',code=code,input=inputs,result=p.get('detail',p.get('error')),status='Observed',source=p['source'],probe=pid,image='files/'+img if img else None))
sessions=read('sessions.json')
for label,title in [('create-and-commit','Create a persistent session'),('resume-and-edit','Resume and edit a session'),('managed-outputs','Save managed render and export outputs'),('throw-after-mutation','Reopen after a failed edit')]:
 x=next(x for x in sessions if x['label']==label);result=x['response']['result'].get('structuredContent',x['response']['result'])
 recipes.append(dict(id='session-'+label,title=title,family='changes',summary='A real local MCP session run with synthetic data. Absolute paths in the raw receipt identify the original capture environment.',kind='session',code=x['input']['code'],input=x['input'],result=result,status='Observed',source='../2026-09-15-artifact-tool-reference/files/runs/sessions.json'))
formulaHelp={x['name']:x for x in help if x['kind']=='formula'}
oracles={x['id'][3:]:x.get('detail',{}) for x in read('oracles.json')}
formulas=[]
for x in read('formula-results.json'):
 h=formulaHelp[x['name']];e=x['examples'][0];value=e.get('value');status='Value returned'
 if isinstance(value,str):
  if 'not implemented' in value:status='Unimplemented text'
  elif value.startswith('#'):status='Excel error'
  elif re.search('Cannot read|not a function|Invalid array length',value):status='Exception-like text'
 formulas.append(dict(id=x['name'],title=x['name'][3:],category=x['category'],summary=h['summary'],notes=h.get('notes',[]),input={'formula':e['formula'],'fixture':'Sheet1 and Data A1:E20: row i = [i,2i,3i,4i,5i], i=1…20'},result=e,status=status,oracle=oracles.get(x['name'][3:]),kind='formula',code=e['formula']))
audit=read('export-audit.json');enum=[x for x in help if x['kind']=='enum'];charts=[]
for type_ in next(x for x in enum if x['name']=='enum.ChartType')['values']:
 a=next(x for x in audit if x['file']=='files/runs/chart-'+type_+'.xlsx');native=[t for c in a['charts'] for t in c['types']]
 charts.append(dict(id='chart-'+type_,title=type_,kind='chart',status='Native chart' if native else 'Omitted from XLSX',input={'type':type_,'fixture':'Category plus two numeric series, four observations.'},result={'nativeChartParts':native,'render':'Timed out' if type_=='boxWhisker' else 'Completed'},image=None if type_=='boxWhisker' else 'files/chart-'+type_+'.png',code='sheet.charts.add('+json.dumps(type_)+', range);',summary='Compare the saved preview with the native Excel-file evidence. The same simple fixture is not suitable for interpreting every chart type.'))
shapes=[]
for i,t in enumerate(next(x for x in enum if x['name']=='enum.ShapeGeometry')['values']):
 shapes.append(dict(id='shape-'+t,title=t,kind='shape',status='Captured',input={'geometry':t},result={'created':True,'customPathsRequired':t=='custom'},image='files/workflow-example.png' if t=='custom' else 'files/Shapes-'+str(i//40+1)+'.png',atlasIndex=i%40,summary='A captured geometry from the installed package. Contact sheets show the original rendered output, including its labels.',code='sheet.shapes.add({geometry:'+json.dumps(t)+', anchor, fill, line'+(', customPaths' if t=='custom' else '')+'});'))
limits=[
 dict(id='totals',title='The cached total can hide a changed table',family='tables',expected='9 throughout, if all three data rows still count.',observed='Existing formula: 9. Fresh formula: 5. After reopening: both 5.',why='showTotals reclassified the final data row. The old calculated value stayed stale.',repair='Reserve the totals row explicitly, then test a fresh structured formula and reopen the file.',input={'quantities':[2,3,4],'showTotals':True},result=probes['V04']['detail'],code='table.showTotals = true;',states=[['Before totals',9],['Existing formula',9],['Fresh formula',5],['After reopening',5]]),
 dict(id='labels',title='A valid-looking assignment can break export',family='charts',expected='Chart labels display and the workbook exports.',observed='The assignment completes; export throws toProto is not a function.',why='Replacing a nested facade with a plain object removes its serialization methods.',repair='Set chart.dataLabels.showValue = true on the existing object.',input=read('api-example-020.json')['originalCode'],result=read('api-example-020.json')['exportError'],code='chart.dataLabels = {showValue:true};'),
 dict(id='validation',title='An input rule is not a JavaScript guard',family='rules',expected='A whole-number rule from 1 to 10 rejects 999.',observed='The programmatic write of 999 is accepted.',why='The rule describes spreadsheet input validation; the mutation path does not enforce it.',repair='Validate incoming values in the wrapper before writing.',input={'min':1,'max':10,'write':999},result=probes['F02']['detail'],code='range.values = [[999]];'),
 dict(id='functions',title='Some formula failures look like ordinary text',family='formulas',expected='OFFSET returns a referenced value.',observed='The engine returns an “is not implemented” string.',why='Checking only #REF! and similar Excel errors misses this failure mode.',repair='Check expected values and unexpected text, and use a verified supported equivalent.',input={'formula':'=OFFSET(A1,1,1)'},result=oracles.get('OFFSET'),code='=OFFSET(A1,1,1)'),
 dict(id='reexport',title='Repeated saving can lose a native feature',family='files',expected='A pivot slicer remains present after import and re-export.',observed='xl/slicers/slicer.xml disappears, while the slicer cache remains.',why='Initial export and import/re-export exercise different feature-preservation paths.',repair='Check the actual native parts required by the intended edit workflow.',input={'workflow':['export','import','export']},result={'lostPart':'xl/slicers/slicer.xml','retained':'slicer cache'},code='await SpreadsheetFile.exportXlsx(reopened);'),
 dict(id='oned',title='Documentation can understate what works',family='sensitivity',expected='The supplied guide says one-variable data tables are unsupported.',observed='Both row and column versions calculated and re-imported correctly.',why='Documentation and the installed runtime do not always agree.',repair='Treat this as evidence for version 2.8.59; keep the exact working fixture.',input={'scenarios':[1,2,3]},result=probes['R04']['detail'],code='sheet.dataTables.add("E4:H5", {rowInput:"B2"});')]
payload={'version':'2.8.59','date':'2026-09-15','families':families,'recipes':recipes,'operations':ops,'apis':apis,'formulas':formulas,'charts':charts,'shapes':shapes,'support':build_support(REF),'limits':limits,'walkthrough':json.loads((ROOT/'data/walkthrough.json').read_text()),'coverage':json.loads((REF/'files/coverage.json').read_text())}
dump(ROOT/'data/field-guide.json',payload)
assets={x.get('image') for x in recipes+charts+shapes if x.get('image')}
for f in assets:shutil.copy2(RUN/Path(f).name,ROOT/f)
sourceFiles=[REF/'files/coverage.json',RUN/'api-help.ndjson',RUN/'api-example-results.json',RUN/'formula-results.json',RUN/'ops.json',RUN/'oracles.json',RUN/'export-audit.json',RUN/'sessions.json']
dump(ROOT/'data/source-receipt.json',{'sources':[{'path':str(x.relative_to(ROOT.parent)),'sha256':hashlib.sha256(x.read_bytes()).hexdigest()} for x in sourceFiles],'supportSources':[{'id':r['id'],'path':r['source'],'sha256':hashlib.sha256((ROOT/r['source']).resolve().read_bytes()).hexdigest(),'sourceTextSha256':hashlib.sha256(r['code'].encode()).hexdigest()} for r in payload['support']], 'counts':{k:len(payload[k]) for k in ['families','recipes','operations','apis','formulas','charts','shapes','support']},'gridConvention':'Workbook cell displays project actual saved state; this interface does not run the artifact calculation engine.'})
print(json.dumps({'counts':{k:len(payload[k]) for k in ['families','recipes','operations','apis','formulas','charts','shapes','support']},'bytes':(ROOT/'data/field-guide.json').stat().st_size,'images':len(assets)}))
