"""Turn supplied scripts and workflow documents into inspectable guide records."""
import json

def build_support(reference):
    base='../2026-09-15-artifact-tool-reference/'
    saved=reference/'files/sources'
    results=json.loads((reference/'files/runs/supplied-examples.json').read_text())
    purposes={
      'quick_start_example':('Build a complete workbook','A first end-to-end builder: create cells, formulas, presentation and saved artifacts.'),
      'formula_trace_and_help':('Explain a calculated result','Trace the dependencies behind a check, and query help with a bounded response.'),
      'chart_suggestions':('Learn chart construction','Create native chart objects, adjust their presentation, render and save them.'),
      'inspect_existing_workbooks':('Read before editing','Inventory an imported workbook and inspect its regions, formulas and drawings.')}
    records=[]
    for r in results:
      n=r['name'];title,why=purposes[n];path='files/sources/package/examples/'+n+'.ts'
      records.append(dict(id='support-'+n,title=title,kind='script',category='Supplied runnable example',status='Executed',summary=why,input={'file':n+'.ts','runtime':'Bundled Node with @oai/artifact-tool 2.8.59','adaptations':r['adaptations']},result=r,code=(reference/path).read_text(),source=base+'files/runs/supplied-examples.json',notes=['The code is the original supplied source. Any adaptation used by the execution harness is listed explicitly.','Source: '+path]))
    path='files/sources/skill/container_tools/mark_artifact_operation_started.mjs'
    records.append(dict(id='support-marker',title='Record that authoring is starting',kind='script',category='Supplied operation marker',status='Source inspected',summary='A required authoring bookkeeping step in the supplied skill. It validates its arguments; it does not build or save a workbook.',input={'argumentOrder':['--operation-kind','create|edit','--expected-output-count','1–100','--output-format','csv|tsv|xls|xlsm|xlsx'],'when':'Once before first authoring, as instructed by the installed skill'},result={'validInvocation':'Silent completion; no file written by the script','invalidInvocation':'Usage on stderr; exit code 2','formatMeaning':'Accepted marker formats are not an exporter capability claim'},code=(reference/path).read_text(),source=base+path,notes=['This page displays the archived source; selecting the record does not invoke the marker.']))
    docs=[
      ('create','Create one rerunnable builder','workflows/create_workflows.md','Create a workbook whose assumptions, calculations and outputs have clear roles.',['Establish the audience, decision and target engine.','Preserve source facts; prepare rectangular writes.','Calculate once, check independent controls, render, export and reopen.']),
      ('edit','Make a focused edit','workflows/edit_workflows.md','Inspect an existing workbook and preserve its conventions while changing the relevant cells.',['Inventory formulas, structure and native objects before editing.','Reuse nearby formulas and formatting.','Check affected dependencies and the exported file.']),
      ('style','Make the workbook readable','style_guidelines.md','Choose hierarchy, spacing, units, number formats and charts for the intended reader.',['Use consistent units and number/date formats.','Respect explicit user instructions and supplied references.','Judge the rendered sheets, not only the code.']),
      ('finance','Structure a financial model','domain_guidance/financial_models.md','Connect periods, assumptions and schedules to useful outputs and reconciliations.',['Keep periods and accounting bases consistent.','Calculate meaningful intermediate results once.','Use independent checks for terminal answers.']),
      ('marketing','Keep performance measures comparable','domain_guidance/marketing_advertising.md','Align populations, time windows and denominators before comparing marketing performance.',['Preserve the scope and grain of source measures.','Aggregate counts and rates appropriately.','Make assumptions and missing data visible.']),
      ('healthcare','Keep context and units traceable','domain_guidance/healthcare.md','Preserve clinical or administrative context when preparing healthcare workbooks.',['Keep units, denominators and source limits explicit.','Distinguish the meaning of each measure.','Use traceable calculations and relevant checks.']),
      ('science','Preserve observations and uncertainty','domain_guidance/scientific_research.md','Keep original measurements, transformations and scientific uncertainty inspectable.',['Retain original observations and units.','Separate source data from calculated transformations.','Use independent numerical and consistency checks.']),
      ('read-only','Answer without unnecessary authoring','references/read_only_qna.md','Use inspection and explanation when the request only needs an answer.',['Read the relevant workbook evidence.','Bound the inspection to the question.','Do not create or edit a file merely to answer a question.']),
      ('images','Use images as reconstruction evidence','references/image-references.md','An image shows layout and appearance; it cannot establish all formulas or hidden workbook state.',['Inspect the reference at useful scale.','Distinguish visible content from missing workbook structure.','Compare reconstructed output to the reference.']),
      ('template','Resolve the intended template','references/template-elicitation.md','Get enough source and layout information to reconstruct the intended workbook.',['Identify what must be preserved.','Resolve material missing requirements.','Use semantic authoring rather than opaque layout replay.']),
      ('google','Route Google Sheets work','routing/google_sheets.md','Use the destination-specific connected workflow when the requested result belongs in Google Sheets.',['Requires connected Google services.','Account-backed creation and edits were not exercised in this study.','Local XLSX success does not establish the remote service behavior.'])]
    for key,title,rel,why,steps in docs:
      path='files/sources/skill/'+rel
      records.append(dict(id='support-'+key,title=title,kind='guidance',category='Supplied workflow guidance',status='Guidance only',summary=why,input={'whenToUse':why,'scope':'Guidance around the package; not an additional API'},result={'workingPattern':steps,'source':path},code=(reference/path).read_text(),source=base+path,notes=['The concise working pattern is a reading aid. The complete archived document is available under Code and saved record.','Instructions from the user and the currently installed skill take precedence over this dated snapshot.']))
    for key,title,filename,why,receipt in [
      ('scenario','Capture scenarios and restore the inputs','workflow-examples.mjs','Change authoritative inputs, calculate and capture labeled outputs, then restore inputs in finally. This harness also exercises custom geometry.','files/runs/workflow-example.json'),
      ('sessions','Persist work across isolated calls','sessions.mjs','Use a stable target, JSON inputs/results and managed output descriptors. Reopen after uncertain outcomes.','files/runs/sessions.json'),
      ('isolation','Isolate risky examples in workers','api-sweep.mjs','Give each API example its own process, fixture, timeout and saved receipt so one failure does not erase the rest.','files/runs/api-example-results.json')]:
      records.append(dict(id='support-'+key,title=title,kind='script',category='Study harness',status='Executed',summary=why,input={'script':filename,'role':'Research harness around the package','runtime':'Bundled Node; local dependencies prepared first'},result={'receipt':receipt,'interpretation':'The complete captured output is linked below.'},code=(reference/filename).read_text(),source=base+receipt,notes=['This is research code from the exploration, not a supplied package example.','It may contain machine-specific defaults; review the reference reproduction section before reuse.']))
    return records
